name: Build

on:
  push:
    branches: [ main, experimental ]
  pull_request:
    branches: [ main, experimental ]
  workflow_dispatch:

jobs:

  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Setup Haxelib
        run: |
          sudo apt-get update
          sudo apt-get install -y libvlc-dev libvlccore-dev

          haxelib setup ~/haxelib
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet

          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Create Version File
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile Linux
        run: |
          haxelib run lime build Project.xml linux \
          --app-version="4.0.0-${{ github.run_id }}" \
          -D officialBuild

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: linuxBuild
          path: export/release/linux/bin


  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Setup Haxelib
        shell: cmd
        run: |
          haxelib setup C:\haxelib
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet

          call .\setup\windows.bat

      - name: Create Version File
        shell: cmd
        run: echo %GITHUB_RUN_ID% > VERSION

      - name: Compile Windows
        run: haxelib run lime build Project.xml windows --app-version="4.0.0-${{ github.run_id }}" -D officialBuild

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windowsBuild
          path: export/release/windows/bin
